- name: Install ClamAV from package URL with apt
  ansible.builtin.apt:
    deb: "{{ clamav_linux_package_url }}"
    state: present
  when: ansible_pkg_mgr == "apt"

- name: Install CalmAV from package URL with dnf
  ansible.builtin.dnf:
    name: "{{ clamav_linux_package_url }}"
    state: present
    disable_gpg_check: true
  when: ansible_pkg_mgr == "dnf"

- name: "If it does no exist, create the directory: {{ freshclam_configuration_path | dirname }}"
  ansible.builtin.file:
    path: "{{ freshclam_configuration_path | dirname }}"
    state: directory
    mode: '0755'

- name: "Copy freshclam.conf to {{ freshclam_configuration_path }}"
  ansible.builtin.template:
    src: freshclam.conf.j2
    dest: "{{ freshclam_configuration_path }}"
    backup: true
    force: true
    owner: root
    group: root
    mode: "0644"
