---
# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

# Debian seems to enable the clamav daemon by default
- name: Disable main clamav daemon
  ansible.builtin.service:
    enabled: false
    name: "{{ clamav_service_name }}"
  when: clamav_install_from_package_manager

- name: Create freshclam service file
  ansible.builtin.template:
    src: freshclam.service.j2
    dest: /etc/systemd/system/{{ freshclam_service_name }}.service
    owner: root
    group: root
    mode: "0644"
  when: not clamav_install_from_package_manager and ansible_service_mgr == "systemd"

- name: Start and enable freshclam
  ansible.builtin.service:
    enabled: true
    name: "{{ freshclam_service_name }}"
    state: started
