---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/geerlingguy/docker-debian10-ansible:latest
    name: debian10-systemd
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/geerlingguy/docker-debian11-ansible:latest
    name: debian11-systemd
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    name: debian12-systemd
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/cisagov/docker-debian13-ansible:latest
    name: debian13-systemd
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/cisagov/docker-kali-ansible:latest
    name: kali-systemd
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
scenario:
  name: debian
verifier:
  directory: ../default/tests
  name: testinfra
